package com.ipotensic.kernel.enums;

/* loaded from: classes2.dex */
public enum CaptureUIType {
    CAPTURE_UI_PHOTO,
    CAPTURE_UI_RECORD,
    CAPTURE_UI_GO,
    CAPTURE_UI_RECORDING,
    CAPTURE_UI_TAKING_PHOTO,
    CAPTURE_UI_TIMER_TAKING_PHOTO,
    CAPTURE_UI_EXIT_TRACK,
    CAPTURE_UI_CANCEL_COUNTDOWN,
    CAPTURE_UI_CANCEL_BACK,
    CAPTURE_UI_PROGRESS
}