package com.ipotensic.baselib.enums;

/* loaded from: classes2.dex */
public enum State {
    STATE_USB_NO_CONNECT,
    STATE_USB_CONNECT_REMOTER,
    STATE_USB_CONNECT_REMOTER_FAIL,
    STATE_USB_CONNECT_FLIGHT,
    STATE_USB_CONNECT_FLIGHT_FAIL,
    STATE_USB_FLIGHT_BOOTLOADER,
    STATE_WIFI_NO_CONNECT,
    STATE_WIFI_CONNECT_REMOTER,
    STATE_WIFI_CONNECT_REMOTER_FAIL,
    STATE_WIFI_CONNECT_FLIGHT,
    STATE_WIFI_CONNECT_FAIL
}